### ISSUE TITLE
Default installation to bower_components

### ISSUE THREAD

**Issue by FinalAngel** [BradDenver/Preen#10]
When setting a custom directory in `.bowerrc`, preen seems to ignore it:

```
{
  "directory": "/static/vendor"
}
```

Is there somewhere an additional setting or am I missing something in the documentation? The `preen` command only gets applied to the `bower_components` directory.

Referring to this line of code: https://github.com/BradDenver/Preen/blob/master/lib/preen.js#L48

**Comment by BradDenver** [comment]
Sorry I have taken so long to respond @FinalAngel I seem to have missed this issue.

I did some testing and could repeat your issue. For me removing the leading slash fixed the issue and didn't cause bower any problems:
```js
{
  "directory": "static/vendor"
}
```

Let me know if that doesnt work for you.
