### ISSUE TITLE
Suggestion on config options

### ISSUE THREAD

**Issue by dacodekid** [BradDenver/Preen#13]
Is it possible to move "preen" filter out from bower.json and pass through Gulp task. For ex:

``` javascript
gulp.task('preen', function(cb) {
    preen.preen({
        filter: { 
                     "jquery": ["dist/*.js"]
                }
    }, cb);
});
```

**Comment by dacodekid** [comment]
Created a pull request here. https://github.com/BradDenver/Preen/pull/14

Now I could pass my 'filters' through Gulp, like below.

``` javascript
//preen
gulp.task('preen', function(cb) {
    preen.preen(
        {
            directory: build_path.vendor,
            filterList: {
                      "preen": {
                        "jquery": 
                          [
                            "dist/*.js"
                          ],
                        "fontawesome":
                          [
                            "css/*",
                            "fonts/*"
                          ]
                      }             
            }
        }, cb);
});

```

**Comment by BradDenver** [comment]
thanks for the input @dacodekid.

What is the use case here? Is the purpose to be able run different (dynamic) filters as part of different gulp tasks?

As I see it the main value of preen is that is that its configured in the same place as everything else for bower, bower.json.

If you are not reading config from bower.json then preen doesn't really offer anything over https://github.com/sindresorhus/del . There is a gulp recipe here https://github.com/gulpjs/gulp/blob/master/docs/recipes/delete-files-folder.md. Do you have anything to add @sindresorhus ?

Please let me know if I am missing something @dacodekid .

**Comment by dacodekid** [comment]
@BradDenver : A use case would be, 
- A template might just start with a _package.json_ & a _gulpfile.js_ - and _bower.json_ file could be created from Gulp. Below is my setup.

``` javascript
gulp.task('bower', function() {
    bower.commands
        .init({interactive: true})
        .on('prompt', function (prompts, callback) {
            inquirer.prompt(prompts, callback);
        })
        .on('end', function(){
            bower.commands
                .install(['jquery', 'fontawesome'], { save: true }, { /* custom config */ })
                .on('end', function (installed) {
                    console.log(installed);
                });
        })
});
```

Now one could manage his/her bower dependency list from gulpfile itself with preconfigured **'preen filters'**. 
- Instead hardcode the config's location to _bower.json_, user gets options.
- May be I misunderstood this, but to my understanding, even though **'del' & 'preen'** does the same job, in context... while 'del' instructs "what to delete and _not_ to delete", preen's tells "what to keep". 
- _[Update]_ With the above case, in case I decide not to maintain _bower.json_ file, I could just use the below task and still use 'preen' to manage 'bower_components".

``` javascript
bower.commands
    .install(['jquery', 'fontawesome'], { save: true }, { /* custom config */ })
    .on('end', function (installed) {
        console.log(installed);
    });
```
